Add retention time to cw loggroup
coralogix/terraform-coralogix-aws pull request #102
Opened 2023-11-13 09:01 UTC by dennischristmann

# Description

This pull request adds the option to specify a retention time of the CloudWatch log group that is created by the lambda, which does the shipping of the S3 log data to Coralogix. In particular, for some log types (like CloudTrail or VPC flow logs) the lambda creates much output, thereby creating large CloudWatch log groups. For most use cases, these logs in CloudWatch are not necessary and a short retention time is sufficient.

# How Has This Been Tested?

The module was instantiated with the new variable set to 7 (i.e., one week retention)  and checked that the resulting CloudWatch Log Group has the corresponding retention time:

module "coralogix-shipper-s3" {
  source = "<local_path>/terraform-coralogix-aws/modules/s3"

  coralogix_region = var.coralogix_region
  custom_url       = var.coralogix_custom_url
  private_key      = var.coralogix_private_key
  application_name = var.coralogix_application_name
  subsystem_name   = var.coralogix_subsystem_name
  s3_bucket_name   = var.bucket_name
  integration_type = "s3"
  s3_key_prefix    = local.s3_key_prefix

  cloudwatch_logs_retention_in_days = 7

  tags = var.custom_tags
}

# Checklist:
- [X ] I have updated the relevant example in the examples directory for the module.
- [ ] I have updated the relevant test file for the module.
- [ ] This change does not affect module (e.g. it's readme file change)

2023-11-15 09:05 UTC, guyrenny requested changes
Hi @dennischristmann , thank you for your suggestion,
Just need to add small changes:

1. When we add a new variable to module we also need to add him in the [readme file](https://github.com/coralogix/terraform-coralogix-aws/blob/master/modules/s3/README.md) of the module and to the variable.tf under the example folder [examples/s3/varibales.tf](https://github.com/coralogix/terraform-coralogix-aws/blob/master/examples/s3/variables.tf)
2. We want to keep track on the changes that we make, so if you could also add an entry in the [changelog](https://github.com/coralogix/terraform-coralogix-aws/blob/master/modules/s3/CHANGELOG.md) file of the module.

2023-11-15 15:10 UTC, dennischristmann commented on modules/s3/main.tf
> +  cloudwatch_logs_retention_in_days       = var.cloudwatch_logs_retention_in_days
Hey @guyrenny ,

I hope I addressed all issues. Regarding the ReadMe and Changelog files, I assumed that they are auto-generated but obviously was wrong :-)

2023-11-20 08:10 UTC, guyrenny approved these changes

2023-11-24 07:06 UTC, dennischristmann commented
Hey @guyrenny , do I need to do anything else? I don't have write access to this repository, so I can't merge / close the pull request.

2023-11-24 09:32 UTC, merged