[Feature] Allow Bucket Destruction via Code
coralogix/terraform-coralogix-aws pull request #104
Opened 2023-11-14 21:43 UTC by hikerspath

# Description

User will end up with the following error message when attempting to destroy presently...

```
│ Error: Instance cannot be destroyed
│
│   on .terraform/modules/coralogix_s3/modules/provisioning/s3-archive/main.tf line 16:
│   16: resource "aws_s3_bucket" "logs_bucket_name" {
│
│ Resource module.coralogix_s3.aws_s3_bucket.logs_bucket_name[0] has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. To avoid this error and continue with the plan, either
│ disable lifecycle.prevent_destroy or reduce the scope of the plan using the -target flag.
```

# How Has This Been Tested?

Setting lifecycle to false and running code manually after downloading the module w/ `terraform init` and then running a `terraform destroy`.

# Checklist:
- [x] I have updated the relevant example in the examples directory for the module.
- [ ] I have updated the relevant test file for the module.
- [ ] This change does not affect module (e.g. it's readme file change)

2023-11-15 08:20 UTC, guyrenny requested changes
Hi @hikerspath, thank you for your suggestion,
Just need to add small changes:
1. When we add a new variable to module we also need to add him in the [readme file](https://github.com/coralogix/terraform-coralogix-aws/blob/master/modules/provisioning/s3-archive/README.md) of the module and to the variable.tf under the example folder [examples/s3-archive/varibales.tf](https://github.com/coralogix/terraform-coralogix-aws/blob/master/examples/s3-archive/varibales.tf)
2. We want to keep track on the changes that we make, so if you could also add an entry in the [changelog](https://github.com/coralogix/terraform-coralogix-aws/blob/master/modules/provisioning/s3-archive/CHANGELOG.md) file of the module. 

Other then this changes everything looks good.

2024-10-08 09:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/coralogix/terraform-coralogix-aws?pullRequest=104) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/coralogix/terraform-coralogix-aws?pullRequest=104) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/coralogix/terraform-coralogix-aws?pullRequest=104) it.</sub>

2024-10-11 14:32 UTC, ShironB commented
Hey @guyrenny / @royfur, 

This feature is very important because currently we have to delete the S3 buckets manually, which causes a drift in Terraform. 

Could you please add this?

2024-10-13 12:29 UTC, closed without merging

2024-10-13 12:33 UTC, guyrenny commented
Hi @ShironB and @hikerspath because there was no update on this PR, I have merged a PR with the changes to fix this issue. You can now force destroy the S3 buckets using the variables `logs_bucket_force_destroy` and `metrics_bucket_force_destroy`

2024-10-13 12:45 UTC, ShironB commented
Thanks @guyrenny !