ECS Enhancements
coralogix/terraform-coralogix-aws pull request #123
Opened 2023-12-27 16:58 UTC by anton-yurchenko

Hey team,

# Description
This PR introduces the following enhancements:

- Lock required dependencies
- Format the module
- Use unique resource names - this will allow to deploy the service multiple times on the same cluster (for configuration tests for example) and to maintain separate definition within the same account/region
- Support user tagging - frequently used for billing and alike
- Use single definition for multiple service deployments - allows centrally maintaining configuration for all the deployments

# How Has This Been Tested?

This PR was not tested

# Checklist:
- [ ] I have updated the relevant example in the examples directory for the module.
- [ ] I have updated the relevant test file for the module.
- [ ] This change does not affect module (e.g. it's readme file change)

2023-12-28 06:02 UTC, frank-ang requested changes
Thanks for the contribution. Suggesting minor changes.

2023-12-29 06:44 UTC, simonweil commented on modules/ecs-ec2/providers.tf
This file is usually named versions.tf

2024-01-01 17:30 UTC, anton-yurchenko commented on modules/ecs-ec2/providers.tf
> +    cloudflare = {
My bad, CTRL+C/V syndrome 😉

2024-01-01 17:33 UTC, anton-yurchenko commented
I have updated the PR as per your commentaries
Thank you

2024-01-02 12:47 UTC, royfur commented
@anton-yurchenko I notice that there is 1 check fail since you didn't update the changelog
once you update it we will be able to merge the changes

2024-01-02 15:55 UTC, merged