Create a Kinesis Firehose module
coralogix/terraform-coralogix-aws pull request #7
Opened 2022-06-13 10:59 UTC by amit-mazor

2022-06-14 06:01 UTC, oded-dd requested changes
Starting to look really good

2022-06-19 07:06 UTC, amit-mazor commented on examples/firehose/selected-metrics-cloudwatch-firehouse/variables.tf
> +  default     = ["EC2", "DynamoDB"]
but its an example I want to show how to include only a few selected namespaces

2022-06-19 07:13 UTC, amit-mazor commented on examples/firehose/selected-metrics-cloudwatch-firehouse/README.md
> +* include_metric_stream_namespaces --> The list of the the desired namespaces, for example: ["EC2", "DynamoDB"]. For the full list of the available namespaces and how they need to be mentioned, pleas
Our docs are not related to these namespaces that AWS allow us to use, 
the goal of this link is to show the users how to select namespaces, our docs dont have this list

2022-06-19 07:40 UTC, amit-mazor commented on examples/firehose/full-cloudwatch-firehose/main.tf
> +  privatekey                       = var.coralogix_privatekey
its true by default so I just deleted the var from here

2022-06-19 07:43 UTC, amit-mazor commented on examples/firehose/selected-metrics-cloudwatch-firehouse/README.md
> +```
added the aws docs link, and kept this list as an example

2022-06-19 12:54 UTC, amit-mazor commented
@oded-dd @avivgold098
* Updated all of the examples - changed the source, the defaults, and of the repeated comments.
* Also, added a new example for deploying multiple firehoses.  
* About the var of the endpoint url, im trying to update it to be based on the region input instead of the full url.

TO DO:
* Add readme
* Add changelolg

2022-06-21 11:11 UTC, avivgold098 approved these changes

2022-06-21 13:24 UTC, merged